export const mockApiData = [
  {
    id: 1,
    name: 'Rottweiler',
    image: 'assets/images/rottweiler.jpg',
    country: 'Germany',
    lifespan: '9-10 years',
    height: '56-68 cm',
    weight: '38-59 kg',
    wool: 'short',
    color: 'black, mahogany',
    group: 'fighting, for protection, for security, sentry',
    price: '700 - 2000$',
    description:
      'Rottweiler dogs have a large, muscular build, a wide, deep chest. The legs are of medium length, strong and also muscular, the neck is medium, massive, the head is large, with a powerful mouth, the ears hang down on the sides of the head on the cheekbones. The tail is usually docked and the color is black and tan.',
  },
  {
    id: 2,
    name: 'Husky (Siberian Husky)',
    image: 'assets/images/husky.jpg',
    country: 'Russia',
    lifespan: '12-15 years',
    height: '51-60 cm',
    weight: '16-27 kg',
    wool: 'medium',
    color: 'black, gray, white, black and white, gray and white, black and tan',
    group: 'for children, watchdogs, sledding',
    price: '500 - 1000$',
    description:
      'The Siberian Husky is a large dog with a muscular and proportionally built body. The limbs are of medium length, the tail is fluffy, saber-shaped, often curved upward, not docked, the hair is long. The muzzle resembles that of a wolf, but wider, the ears are erect and of medium size, and the eyes are blue. Sometimes one eye is blue and the other has a different color.',
  },
  {
    id: 3,
    name: 'Alaskan Malamute',
    image: 'assets/images/malamute.jpg',
    country: 'USA (Alaska)',
    lifespan: '13-16 years',
    height: '56-66 cm',
    weight: '32-43 kg',
    wool: 'medium',
    color: 'white and light gray to black',
    group: 'for children, for protection, hunting, sledding',
    price: '500 - 3500$',
    description:
      'The Alaskan Malamute dog breed resembles large wolves, has a large build, a wide, powerful chest, limbs of medium length, muscular and very strong. The tail is fluffy saber-shaped. These animals are generally distinguished by their enormous strength and endurance, which is visible in their every movement. The head is large, the ears are erect, and the scruff of the neck is clearly visible. The wool is long.',
  },
  {
    id: 4,
    name: 'Wolfdog',
    image: 'assets/images/wolfdog.jpg',
    country: 'Russia',
    lifespan: '20-25 years',
    height: '62-67 cm',
    weight: '40-50 kg',
    wool: 'long',
    color: 'black, gray',
    group: 'for protection, guard',
    price: '300 - 700$',
    description:
      'Порода волкособ - это животные крупных размеров, весом 40-50 кг, с худощавым, но мускулистым и очень сильным телом. Фактически, они внешне очень напоминают волков - уши прямостоящие, морда вытянутая, конечности чуть длиннее среднего, взгляд пронзительный и очень умный. Хвост средней длины, пушистый. Окрас может быть черным или серым.',
  },
];
